### ISSUE TITLE
How to use this test harness?

### ISSUE THREAD

**Issue by kennethlimcp** [mmdaz/feature_testing_chat_bots#1]
Hello! 

Is this a Work In Progress or do you have more information on how a telegram bot can be end-to-end tested with this setup?

Thanks!

**Comment by mmdaz** [comment]
> Hello!
> 
> Is this a Work In Progress or do you have more information on how a telegram bot can be end-to-end tested with this setup?
> 
> Thanks!

Hey!
I'm sorry for the delay in response.
As you see in [test.py](https://github.com/mmdaz/feature_testing_chat_bots/blob/master/test.py) we use mock of bot and updater of telegram. and so we want to test just the scenario of the chatbot.
